### ISSUE TITLE
Miss spelled env var

### ISSUE THREAD

**Issue by gaetanmuck** [geovistory/dev-stack#1]
Got a warning message, resulting in an error:
`WARN[0000] The "REDPANDA_SCHEMA_REGISTRY_PORT" variable is not set. Defaulting to a blank string.`

After looking at the `.env` file, it seems that the variable is missed spelled:
got: `REDPANDA_SCHEMA_REGISTRY`
should: `REDPANDA_SCHEMA_REGISTRY_PORT`

**Comment by dferhod** [comment]
Fixed in last commit
