### ISSUE TITLE
docker compose

### ISSUE THREAD

**Issue by gaetanmuck** [geovistory/dev-stack#2]
We discussed the docker update going from `docker-compose` to `docker compose`. 
I do not remember our conclusions. 

I observe on my side: (in `scripts/build`) if I use `docker-compose` it does not work at all, I have to use `docker compose`. Is it also the same for others?

**Comment by gaetanmuck** [comment]
Same for `scripts/down` and `scripts/up`

**Comment by joschne** [comment]
In my memory 
- `docker compose` replaces  `docker-compose`. 
- we were able to make it running with `docker compose` on your local copy. 

If it runs on your side, also for `scripts/down` and `scripts/up`, please commit and push directly to main.

**Comment by gaetanmuck** [comment]
Done
